apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-game    
  labels:
    app: board-game-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-game-app
  template:
    metadata:
      labels:
        app: board-game-app
    spec:
       containers:
       - name: jforjava
         image: vishv3432/board-game:latest
         ports:
         - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: board-game
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector: 
    app: board-game-app